Repository OSWeekends/formula-uc3m, pull requests merged in 2018-04, with the labels that each got.

#27 Feature/client scaffold
  .gitignore
  .travis.yml
  build.sh
  client/.babelrc
  client/.editorconfig
  client/.eslintignore
  client/.eslintrc.js
  client/.gitignore
  client/.postcssrc.js
  client/README.md
  client/build/build.js
  client/build/check-versions.js
  client/build/logo.png
  client/build/utils.js
  client/build/vue-loader.conf.js
  client/build/webpack.base.conf.js
  client/build/webpack.dev.conf.js
  client/build/webpack.prod.conf.js
  client/config/dev.env.js
  client/config/index.js
  client/config/prod.env.js
  client/config/test.env.js
  client/index.html
  client/package-lock.json
  client/package.json
  client/src/App.vue
  client/src/assets/logo.png
  client/src/components/HelloWorld.vue
  client/src/components/Mockup.vue
  client/src/main.js
  client/src/router/index.js
  client/static/.gitkeep
  client/test/unit/.eslintrc
  client/test/unit/jest.conf.js
  client/test/unit/setup.js
  client/test/unit/specs/HelloWorld.spec.js
  client/test/unit/specs/Mockup.spec.js
  mockup/index.html
  package-lock.json
Labels: front

#26 Primera implementación del servidor.
  .travis.yml
  README.md
  build.sh
  server/.env.example
  server/.eslintrc
  server/.osweekends/img/OSW-project-GitHub-template-footer.jpg
  server/.osweekends/img/OSW-project-GitHub-template-header.jpg
  server/.osweekends/img/fuc3m-logo.png
  server/README.md
  server/gulpfile.js
  server/index.js
  server/package-lock.json
  server/package.json
  server/src/public/index.html
  server/src/routes/index.js
  server/test/index.js
Labels: Back, Mejoras

#30 Add mosca server. Remove mongoose dependency.
  server/.env.example
  server/index.js
  server/package-lock.json
  server/package.json
  server/src/mqtt/mosca.js
  server/src/public/index.html
Labels: Back

#33 Mejoras de la automatización del servidor y crear el faker para los datos en tiempo real.
  .gitignore
  build.sh
  client/index.html
  server/.eslintrc
  server/README.md
  server/index.js
  server/package.json
  server/src/mqtt/_mosca.html
  server/src/mqtt/faker.js
  server/src/mqtt/mosca.js
  server/src/public/static/.gitkeep
Labels: Back, Mejoras, front
